### ISSUE TITLE
"Illegal parameter entity reference syntax" on W3C DTD for SMIL 3.0

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-dtd-parser#1]
Using dtd-parser trunk code I cannot parse W3C SMIL DTDs. I'm using XJC
2.2.3 to generate JAXB classes for SMIL 3.0:

----- console output -----
$xjc -dtd -d
/data/Dev/Java/XML/SMIL/w3c/org.w3c.smil30.dtd/src/output/java -p
org.w3c.smil30 /data/Dev/Java/XML/SMIL/w3c/DTD/SMIL30Language.dtd
parsing a schema...
[ERROR] Illegal parameter entity reference syntax
line 81 of [file:/data/Dev/Java/XML/SMIL/w3c/DTD/SMIL-layout.mod](file:/data/Dev/Java/XML/SMIL/w3c/DTD/SMIL-layout.mod)

Failed to parse a schema.

* * *

In the extract below line 81 is %SMIL.common-layout-attrs;
----- dtd extract -----

<!ENTITY % SMIL.region.qname "region">
<!ELEMENT %SMIL.region.qname; %SMIL.region.content;>
<!ATTLIST %SMIL.region.qname; %SMIL.region.attrib;
%SMIL.Core.attrib;
%SMIL.I18n.attrib;
%SMIL.backgroundColor.deprecated.attrib;
%SMIL.common-layout-attrs;
%SMIL.region-attrs;
regionName NMTOKEN #IMPLIED
>

* * *

I really don't see what's wrong, and I doubt W3C would produce invalid
DTD.
So I guess it's some sort of bug in dtd-parser.

DTDs can be downloaded at this url:
[http://www.w3.org/TR/SMIL/DTD.zip](http://www.w3.org/TR/SMIL/DTD.zip)

More info on SMIL DTDs:
[http://www.w3.org/TR/SMIL/smil-DTD.html](http://www.w3.org/TR/SMIL/smil-DTD.html)

Any help would be great.

Merry Xmas!
#### Environment
Arch Linux 64 bit, JDK 6
#### Affected Versions
[current]

**Comment by antoniosanct** [comment]
@lukasj 
jaxb-dtd-parser parses W3C SMIL 3.0 editing 'smil-attribs-1.mod', according to the next entity declaration:


  <!ENTITY % SMIL.backgroundOpacity.attrib "
   %SMIL.pfx;backgroundOpacity     CDATA    '100&#38;#38;#38;#37;'
  ">

In line 218, removing '&' character because it doesn't expect '&#' in external entity. I'm not sure about if it is a bug or an unexpected char in entity declaration.

Regards,
Antonio.

**Comment by lukasj** [comment]
it looks to me like a bug in the DTD, where the definition should be:

```
%SMIL.pfx;backgroundOpacity     CDATA    '100&#37;'
```

feel free to reopen if you think there is something dtd parser can do.
