### ISSUE TITLE
Unclear License Type

### ISSUE THREAD

**Issue by BeJot77** [eclipse-ee4j/jaxb-dtd-parser#25]
License file says this component is under BSD-3-Clause license, while notice file says it's under EPL-1.0 license. Which one is it then?

**Comment by BeJot77** [comment]
It's EDL, my bad

**Comment by lukasj** [comment]
> The Eclipse Distribution License is an OSI Approved Open Source License by means of the New BSD License.

see https://www.eclipse.org/org/documents/edl-v10.php
