### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-dtd-parser#5]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
CICD is on new Jenkins infrastructure so scripting will differ from old Jenkins.
Jenkins URL: https://jenkins.eclipse.org/jaxb-impl
Job: https://jenkins.eclipse.org/jaxb-impl/job/dtd-parser-master-build/
I'm playing with it in paralel with eclipse guys. Build is passing, but configuration is still far from ideal state.
TODO:
- git assess trough SSH (not working yet)
- ssh agent plugin to pass credentials into shell script environment
- java 9 (not available in Docker image)
- missing JAVA_HOME in environment
- maven repository caching between jobs

**Comment by Tomas-Kraus** [comment]
Simple continuous build is available at https://jenkins.eclipse.org/jaxb-impl/job/dtd-parser-master-build/
